backend/models/Area.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "areas".
 *
 * @property int $id
 * @property string $name
 * @property string $farming_culture
 * @property string $area
 *
 * @property AreasTractors[] $areasTractors
 */
class Area extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'areas';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['area'], 'integer'],
            [['name', 'farming_culture'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'farming_culture' => 'Farming Culture',
            'area' => 'Area',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreasTractors()
    {
        return $this->hasMany(AreasTractors::className(), ['area_id' => 'id']);
    }
}

backend/controllers/AreaController.php
<?php

namespace backend\controllers;

use yii\rest\ActiveController;

class AreaController extends ActiveController
{
    public $modelClass = 'backend\models\Area';

    public function behaviors() {

        return array_merge(parent::behaviors(), [


            $behaviors['corsFilter']  = [
                'class' => \yii\filters\Cors::className(),
                'cors'  => [
                    // restrict access to domains:
                    'Origin'                           => ['*'],
                    'Access-Control-Request-Method'    => ['GET','POST','PUT','DELETE','OPTIONS'],
                    'Access-Control-Request-Headers' => ['*'],
                    'Access-Control-Allow-Credentials' => true,
                    'Access-Control-Max-Age'           => 3600,                 // Cache (seconds)
                ],
            ]

        ]);
    }

}

frontend/controllers/AreaController.php
<?php
/**
 * Created by PhpStorm.
 * User: Trayan Zlatanov
 * Date: 3/21/2018
 * Time: 7:26 PM
 */

namespace frontend\controllers;


use yii\filters\VerbFilter;
use yii\web\Controller;

class AreaController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays areas list.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays new area form.
     *
     * @return string
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Displays edit area form.
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $this->view->params['id'] = $id;
        return $this->render('edit');
    }

}

frontend/views/area/edit.php
<?php

/* @var $this yii\web\View */

$this->title = 'Area edit';

$this->registerJsFile('js/area/area_edit.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas', ['area/index']) ?>
    </li>
    <li class="breadcrumb-item active">Edit area</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">Edit area</div>
        <div class="card-body">
            <form id="area-form">
                <div class="form-group">
                    <label for="name">Enter Name</label>
                    <input type="text" name="name" class="form-control" id="name" value="" placeholder="Enter Name" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter farming culture</label>
                    <input type="text" name="farming_culture" class="form-control" id="farming_culture" value="" placeholder="Enter farming culture" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter area</label>
                    <input type="number" name="area" class="form-control" id="area" value="" placeholder="Enter area" required>
                </div>
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
                <input type="hidden" id="area_id" value="<?php echo $this->params['id']?>">
            </form>
        </div>
    </div>
</div>

frontend/views/area/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Areas list';

$this->registerJsFile('js/area/area_list.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas', ['area/index']) ?>
    </li>
    <li class="breadcrumb-item active">List</li>
</ol>
<?= \yii\helpers\Html::a('<i class="fa fa-plus"></i> Create new area', ['area/new'], ['class' => 'btn btn-primary btn-success float-right']) ?>
<div class="table-responsive">
    <table class="table table-bordered" id="area-table" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Name</th>
            <th>Farming culture</th>
            <th>Area</th>
            <th style="width: 120px">Actions</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>

frontend/views/area/new.php
<?php

/* @var $this yii\web\View */

$this->title = 'New Area';

$this->registerJsFile('js/area/area_new.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas', ['area/index']) ?>
    </li>
    <li class="breadcrumb-item active">Create new area</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">Create new area</div>
        <div class="card-body">
            <form id="area-form">
                <div class="form-group">
                    <label for="name">Enter Name</label>
                    <input type="text" name="name" class="form-control" id="name" value="" placeholder="Enter Name" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter farming culture</label>
                    <input type="text" name="farming_culture" class="form-control" id="farming_culture" value="" placeholder="Enter farming culture" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter area</label>
                    <input type="number" name="area" class="form-control" id="area" value="" placeholder="Enter area" required>
                </div>
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>