backend/models/AreasTractors.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "areas_tractors".
 *
 * @property int $id
 * @property int $area_id
 * @property int $tractor_id
 * @property string $treated_area
 * @property string $treated_area_date
 *
 * @property Areas $area
 * @property Tractors $tractor
 */
class AreasTractors extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'areas_tractors';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['area_id', 'tractor_id'], 'required'],
            [['area_id', 'tractor_id'], 'integer'],
            [['treated_area_date'], 'safe'],
            [['treated_area'], 'string', 'max' => 255],
            [['area_id'], 'exist', 'skipOnError' => true, 'targetClass' => Area::className(), 'targetAttribute' => ['area_id' => 'id']],
            [['tractor_id'], 'exist', 'skipOnError' => true, 'targetClass' => Tractor::className(), 'targetAttribute' => ['tractor_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'area_id' => 'Area ID',
            'tractor_id' => 'Tractor ID',
            'treated_area' => 'Treated Area',
            'treated_area_date' => 'Treated Area Date',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getArea()
    {
        return $this->hasOne(Area::className(), ['id' => 'area_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTractor()
    {
        return $this->hasOne(Tractor::className(), ['id' => 'tractor_id']);
    }
}

frontend/controllers/AreasTractorsController.php
<?php
/**
 * Created by PhpStorm.
 * User: Trayan Zlatanov
 * Date: 3/21/2018
 * Time: 7:26 PM
 */

namespace frontend\controllers;


use yii\filters\VerbFilter;
use yii\web\Controller;

class AreasTractorsController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays areas tractors list.
     *
     * @return string
     */
    public function actionIndex()
    {
        $requestParams = \Yii::$app->getRequest()->getBodyParams();
        if (empty($requestParams)) {
            $requestParams = \Yii::$app->getRequest()->getQueryParams();
        }

        $this->view->params['areaName'] = (isset($requestParams['area_name'])) ? $requestParams['area_name'] : '';
        $this->view->params['tractorName'] = (isset($requestParams['tractor_name'])) ? $requestParams['tractor_name'] : '';
        $this->view->params['farmingCulture'] = (isset($requestParams['farming_culture'])) ? $requestParams['farming_culture'] : '';
        $this->view->params['date'] =  (isset($requestParams['treated_area_date']) && $requestParams['treated_area_date'] != '')
            ? date('Y-m-d', strtotime($requestParams['treated_area_date'])) : '';

        return $this->render('index');
    }

    /**
     * Displays new area tractor form.
     *
     * @return string
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Displays edit area tractor form.
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $this->view->params['id'] = $id;
        return $this->render('edit');
    }

}

frontend/views/areas-tractors/edit.php
<?php

/* @var $this yii\web\View */

$this->title = 'Area to tractor edit';

$this->registerJsFile('js/areas-tractors/areas-tractors_edit.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas to tractors', ['areas-tractors/index']) ?>
    </li>
    <li class="breadcrumb-item active">Edit area to tractor</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">Edit area to tractor</div>
        <div class="card-body">
            <form id="areas-tractors-form">
                <div class="form-group">
                    <label for="area_id">Choose area</label>
                    <select name="area_id" id="area_id" class="form-control" required>
                        <option value="" data-max-area="0"></option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="tractor_id">Choose tractor</label>
                    <select name="tractor_id" id="tractor_id" class="form-control" required>
                        <option value=""></option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Enter treatment area</label>
                    <input type="number" name="treated_area" class="form-control" id="treated_area" value="" placeholder="Enter treatment area" max="0" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter date</label>
                    <input type="date" name="treated_area_date" class="form-control" id="treated_area_date" value="" placeholder="Enter date" required>
                </div>
                <input type="hidden" id="areas_tractors_id" value="<?php echo $this->params['id']?>">
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>

frontend/views/areas-tractors/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Areas to tractors list';

$this->registerJsFile('js/areas-tractors/areas-tractors-list.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas to tractors', ['areas-tractors/index']) ?>
    </li>
    <li class="breadcrumb-item active">List</li>
</ol>
<?= \yii\helpers\Html::a('<i class="fa fa-plus"></i> Create new area to tractor', ['areas-tractors/new'], ['class' => 'btn btn-primary btn-success float-right']) ?>
<div class="row">
    <div class="card mx-auto col-md-12">
        <div class="card-header">Edit tractor</div>
        <div class="card-body">
            <form action="/index.php">
                <input type="hidden" name="r" value="areas-tractors">
                <div class="row">
                    <div class="form-group col-md-3">
                        <label for="area_name">Area</label>
                        <input type="text" name="area_name" class="form-control" id="area_name" value="<?=$this->params['areaName']?>" placeholder="Filter by Area Name">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="tractor_name">Tractor</label>
                        <input type="text" name="tractor_name" class="form-control" id="tractor_name" value="<?=$this->params['tractorName']?>" placeholder="Filter by Tractor Name">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="farming_culture">Farming culture</label>
                        <input type="text" name="farming_culture" class="form-control" id="farming_culture" value="<?=$this->params['farmingCulture']?>" placeholder="Filter by Farming culture">
                    </div>
                    <div class="form-group col-md-3">
                        <label for="farming_culture">Date</label>
                        <input type="date" name="treated_area_date" class="form-control" id="treated_area_date" value="<?=$this->params['date']?>" placeholder="Filter by Date">
                    </div>
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-2">Search</button>
                </div>
            </form>
        </div>
    </div>
</div>
<div class="table-responsive">
    <table class="table table-bordered" id="areas-tractors-table" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Area</th>
            <th>Farming culture</th>
            <th>Tractor</th>
            <th>Date</th>
            <th>Treated area</th>
            <th style="width: 120px">Actions</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
        <tfoot>
            <tr>
                <th colspan="4">Total</th>
                <th id="treated-area-total"></th>
                <th></th>
            </tr>
        </tfoot>
    </table>
</div>

frontend/views/areas-tractors/new.php
<?php

/* @var $this yii\web\View */

$this->title = 'New Area to tractor';

$this->registerJsFile('js/areas-tractors/areas-tractors_new.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Areas to tractors', ['areas-tractors/index']) ?>
    </li>
    <li class="breadcrumb-item active">New Area to tractor</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">New Area to tractor</div>
        <div class="card-body">
            <form id="areas-tractors-form">
                <div class="form-group">
                    <label for="area_id">Choose area</label>
                    <select name="area_id" id="area_id" class="form-control" required>
                        <option value="" data-max-area="0"></option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="tractor_id">Choose tractor</label>
                    <select name="tractor_id" id="tractor_id" class="form-control" required>
                        <option value=""></option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="name">Enter treatment area</label>
                    <input type="number" name="treated_area" class="form-control" id="treated_area" value="" placeholder="Enter treatment area" max="0" required>
                </div>
                <div class="form-group">
                    <label for="name">Enter date</label>
                    <input type="date" name="treated_area_date" class="form-control" id="treated_area_date" value="" placeholder="Enter date" required>
                </div>
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>