backend/models/Tractor.php
<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "tractors".
 *
 * @property int $id
 * @property string $name
 *
 * @property AreasTractors[] $areasTractors
 */
class Tractor extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tractors';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAreasTractors()
    {
        return $this->hasMany(AreasTractors::className(), ['tractor_id' => 'id']);
    }
}

backend/controllers/TractorController.php
<?php

namespace backend\controllers;

use yii\rest\ActiveController;

class TractorController extends ActiveController
{
    public $modelClass = 'backend\models\Tractor';

    public function behaviors() {

        return array_merge(parent::behaviors(), [


            $behaviors['corsFilter']  = [
                'class' => \yii\filters\Cors::className(),
                'cors'  => [
                    // restrict access to domains:
                    'Origin'                           => ['*'],
                    'Access-Control-Request-Method'    => ['GET','POST','PUT','DELETE','OPTIONS'],
                    'Access-Control-Request-Headers' => ['*'],
                    'Access-Control-Allow-Credentials' => true,
                    'Access-Control-Max-Age'           => 3600,                 // Cache (seconds)
                ],
            ]

        ]);
    }
}

frontend/controllers/TractorController.php
<?php
/**
 * Created by PhpStorm.
 * User: Trayan Zlatanov
 * Date: 3/21/2018
 * Time: 7:26 PM
 */

namespace frontend\controllers;


use yii\filters\VerbFilter;
use yii\web\Controller;

class TractorController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays tractors list.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Displays new tractor form.
     *
     * @return string
     */
    public function actionNew()
    {
        return $this->render('new');
    }

    /**
     * Displays edit tractor form.
     *
     * @return string
     */
    public function actionEdit($id)
    {
        $this->view->params['id'] = $id;
        return $this->render('edit');
    }

}

frontend/views/tractor/edit.php
<?php

/* @var $this yii\web\View */

$this->title = 'Tractor edit';

$this->registerJsFile('js/tractor/tractor_edit.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Tractors', ['tractor/index']) ?>
    </li>
    <li class="breadcrumb-item active">Edit tractor</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">Edit tractor</div>
        <div class="card-body">
            <form id="tractor-form">
                <div class="form-group">
                    <label for="name">Enter Name</label>
                    <input type="text" name="name" class="form-control" id="name" value="" placeholder="Enter Name" required>
                </div>
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
                <input type="hidden" id="tractor_id" value="<?php echo $this->params['id']?>">
            </form>
        </div>
    </div>
</div>

frontend/views/tractor/index.php
<?php

/* @var $this yii\web\View */

$this->title = 'Tractors list';

$this->registerJsFile('js/tractor/tractor_list.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Tractors', ['tractor/index']) ?>
    </li>
    <li class="breadcrumb-item active">List</li>
</ol>
<?= \yii\helpers\Html::a('<i class="fa fa-plus"></i> Create new tractor', ['tractor/new'], ['class' => 'btn btn-primary btn-success float-right']) ?>
<div class="table-responsive">
    <table class="table table-bordered" id="tractor-table" width="100%" cellspacing="0">
        <thead>
        <tr>
            <th>Name</th>
            <th style="width: 120px">Actions</th>
        </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>

frontend/views/tractor/new.php
<?php

/* @var $this yii\web\View */

$this->title = 'New tractor';

$this->registerJsFile('js/tractor/tractor_new.js',['depends' => [
    \yii\web\JqueryAsset::className()
]]);

?>
<!-- Breadcrumbs-->
<ol class="breadcrumb">
    <li class="breadcrumb-item">
        <?= \yii\helpers\Html::a('Tractors', ['tractor/index']) ?>
    </li>
    <li class="breadcrumb-item active">Create new tractor</li>
</ol>
<div class="row">
    <div class="card mx-auto col-md-10">
        <div class="card-header">Create new tractor</div>
        <div class="card-body">
            <form id="tractor-form">
                <div class="form-group">
                    <label for="name">Enter Name</label>
                    <input type="text" name="name" class="form-control" id="name" value="" placeholder="Enter Name" required>
                </div>
                <div class="row">
                    <button type="submit" id="save" class="btn btn-primary btn-block col-md-3">Save</button>
                </div>
            </form>
        </div>
    </div>
</div>